
spring:
  application:
    name: service-a
server:
  port: 8030

eureka: 
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      healthcheck:
      enabled: true
  instance:
    appname: service-a
    preferIpAddress: true

